source 'https://rubygems.org'
group :nanoc do
  gem 'guard-nanoc'
end
gem 'adsf'
gem 'adsf-live'
gem 'webrick'
gem 'nanoc', '~> 4.3'
gem 'kramdown'
gem 'steep'
gem 'pandoc-ruby'
gem 'builder'
gem 'typogruby'
gem 'nokogiri'
gem 'i18n'
