# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Long build an deploy

on: workflow_dispatch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2.3.1
        
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
    
    - name: Cache texlive
      id: cache-tl
      uses: actions/cache@v2
      with:
        path: ~/texlive
        key: texlive4
    
    - name: Install texlive
      if: steps.cache-tl.outputs.cache-hit != 'true'
      run: |
        curl -sLO https://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
        mkdir install-tl
        tar -xf install-tl-unx.tar.gz --directory=install-tl --strip-components=1
        cd install-tl
        ./install-tl -profile "$GITHUB_WORKSPACE/texlive.profile"
    
    - name: Add texlive to PATH
      run: echo "$HOME/texlive/bin/x86_64-linux" >> $GITHUB_PATH
      
    - name: Install pandoc and pdf2svg
      run: |
        curl -sLO https://github.com/jgm/pandoc/releases/download/2.14.0.2/pandoc-2.14.0.2-1-amd64.deb
        sudo dpkg -i pandoc-2.14.0.2-1-amd64.deb
        sudo apt-get install pdf2svg
        
    - name: Build
      run: bundle exec nanoc
    
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: output # The folder the action should deploy.
